# -*- coding: utf-8 -*-
"""exoplanetas-regresion-lineal

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B5hDqPFSlbIZDCffCM61CCkAn2oX_9Wp
"""

import pandas as pd
   import numpy as np
   import matplotlib.pyplot as plt
   import seaborn as sns
   from sklearn.model_selection import train_test_split
   from sklearn.linear_model import LinearRegression
   from sklearn.metrics import r2_score, mean_squared_error

   # Simulación dataset NASA Exoplanet Archive
   np.random.seed(42)
   n = 500
   data = {
       'periodo_orbital': np.random.exponential(50, n),
       'radio_planeta': np.random.lognormal(0.5, 0.8, n),
       'temp_estrella': np.random.normal(5500, 800, n),
       'distancia_estrella': np.random.uniform(0.5, 5, n)
   }
   df = pd.DataFrame(data)
   df['masa_planeta'] = 0.3*df['radio_planeta'] + 0.1*df['periodo_orbital'] + 0.001*df['temp_estrella'] + np.random.normal(0,0.5,n)

   # Modelo de regresión
   X = df[['periodo_orbital', 'radio_planeta', 'temp_estrella', 'distancia_estrella']]
   y = df['masa_planeta']
   X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

   model = LinearRegression()
   model.fit(X_train, y_train)
   y_pred = model.predict(X_test)

   # Resultados
   r2 = r2_score(y_test, y_pred)
   print(f"R² Score: {r2:.3f}")
   print(f"RMSE: {np.sqrt(mean_squared_error(y_test, y_pred)):.3f}")

   # Gráfico
   plt.figure(figsize=(8,6))
   plt.scatter(y_test, y_pred, alpha=0.6)
   plt.plot([y.min(), y.max()], [y.min(), y.max()], 'r--')
   plt.xlabel('Masa Real')
   plt.ylabel('Masa Predicha')
   plt.title(f'Predicción de Masa de Exoplanetas - R²: {r2:.3f}')
   plt.savefig('prediccion_masa.png')
   plt.show()